namespace FrontEnd.Commons.Tokens;

public enum TokenType
{
    Float,
    Integer,
    String,
    Char,
    Comment,
    Keyword,
    Identifier,
    Terminator,
    Comparator,
    Logical,
    Math,
    Null,
    Parenthesis,
    EOF,
    AsLongAsLoop,
    UntilLoop,
    Conditional,
    Define,
    Set,
    AccessorPRIVATE,
    With,
    RoundBracketsOpening,
    RoundBracketsClosing,
    CurlyBracesClosing,
    CurlyBracesOpening,
    SquareBracketsClosing,
    SquareBracketsOpening,
    Comma,
    Nothing,
    Returning,
    As,
    Accessor
}