namespace FrontEnd.Commons.Tokens;

public enum TokenType
{
    Float,
    Integer,
    Text,
    Identifier,
    FullStop,
    Comparator,
    And,
    Mod,
    EOF,
    Define,
    Set,
    AccessorPRIVATE,
    With,
    RoundBracketsOpening,
    RoundBracketsClosing,
    CurlyBracesClosing,
    CurlyBracesOpening,
    SquareBracketsClosing,
    SquareBracketsOpening,
    Comma,
    Nothing,
    Returning,
    As,
    Accessor,
    To,
    Output,
    Minus,
    Add,
    Divide,
    Multiply,
    Or
}